# Generated by Django 3.2.5 on 2021-07-29 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0003_auto_20210729_1659'),
        ('commentcrud', '0003_alter_comment_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Human',
        ),
    ]
