# Generated by Django 3.2.5 on 2021-08-05 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='q_comment',
            old_name='post',
            new_name='qna',
        ),
        migrations.RenameField(
            model_name='q_like',
            old_name='post',
            new_name='qna',
        ),
    ]
