# Generated by Django 3.2.5 on 2021-07-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
