# Generated by Django 3.2.5 on 2021-08-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210803_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='portfolio_isPrivate',
            field=models.BooleanField(default=True),
        ),
    ]
