# Generated by Django 3.2.5 on 2021-07-29 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0003_auto_20210729_1659'),
        ('commentcrud', '0002_rename_commentcrud_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human.humanlog'),
        ),
    ]
