# Generated by Django 3.2.5 on 2021-07-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('logo', models.URLField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_date_str', models.CharField(blank=True, max_length=20, null=True)),
                ('career', models.CharField(max_length=20)),
                ('academic', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=100)),
            ],
        ),
    ]
