# Generated by Django 3.2.5 on 2021-07-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruit',
            name='logo',
        ),
        migrations.AddField(
            model_name='recruit',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='area',
            field=models.CharField(max_length=20),
        ),
    ]
