# Generated by Django 3.2.5 on 2021-07-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20210727_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='scrap_count',
            field=models.IntegerField(default=0),
        ),
    ]
