# Generated by Django 3.2.5 on 2021-07-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_detail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_github',
            field=models.URLField(blank=True, null=True),
        ),
    ]
