# Generated by Django 3.2.5 on 2021-07-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210728_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_detail',
            field=models.CharField(max_length=50),
        ),
    ]
