# Generated by Django 3.2.5 on 2021-07-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_project_project_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_detail',
            field=models.CharField(max_length=50, verbose_name='사용 언어나 프레임워크'),
        ),
    ]
